import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API='https://ai-powered-aurora-grand-hotel-guest.onrender.com/api';
function App(){
 const [messages,setMessages]=useState([{role:'assistant',text:'Welcome to Aurora Grand Hotel! Ask me about rooms, amenities, policies, or availability.'}]);
 const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [form,setForm]=useState({checkIn:'',checkOut:'',adults:2}); const [showForm,setShowForm]=useState(false);
 async function send(text=input){if(!text.trim()||loading)return;setMessages(m=>[...m,{role:'user',text}]);setInput('');setLoading(true);try{const r=await fetch(API+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:messages})});const d=await r.json();setMessages(m=>[...m,{role:'assistant',text:d.message,data:d.data}]);if(d.type==='need_availability')setShowForm(true);}catch(e){setMessages(m=>[...m,{role:'assistant',text:'Sorry, I could not connect to the server. Please make sure the backend is running.'}]);}finally{setLoading(false)}}
 async function availability(e){e.preventDefault();setLoading(true);try{const r=await fetch(API+'/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setMessages(m=>[...m,{role:'assistant',text:d.ok?'Availability results:':d.error,data:d}]);}catch(e){setMessages(m=>[...m,{role:'assistant',text:'Availability service failed. Please try again.'}]);}finally{setLoading(false)}}
 return <main><header><div><h1>✦ Aurora Grand</h1><span>Hotel Guest Assistant</span></div><button onClick={()=>setShowForm(!showForm)}>Check Availability</button></header><section className="chat">{messages.map((m,i)=><div className={'row '+m.role} key={i}><div className="bubble">{m.text}{m.data?.rooms&&<div className="rooms">{m.data.rooms.length?m.data.rooms.map((r,j)=><article key={j}><b>{r.name}</b><p>{r.description}</p><strong>₹{r.pricePerNight}/night</strong><br/>Total: ₹{r.total}</article>):<p>No matching rooms found.</p>}</div>}</div></div>)}{loading&&<div className="row assistant"><div className="bubble">Thinking…</div></div>}</section>{showForm&&<form className="availability" onSubmit={availability}><h3>Find a room</h3><label>Check-in<input type="date" required value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></label><label>Check-out<input type="date" required value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></label><label>Guests<input type="number" min="1" max="10" required value={form.adults} onChange={e=>setForm({...form,adults:Number(e.target.value)})}/></label><button>Search rooms</button></form>}<div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about the hotel…"/><button onClick={()=>send()}>Send</button></div><div className="suggestions">{['What time is check-in?','Do you have a swimming pool?','Is breakfast included?','Which room fits 3 guests?'].map(x=><button onClick={()=>send(x)} key={x}>{x}</button>)}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
